{
 "title": "Remnawave - Full Monitoring",
 "tags": [ "remnawave-monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"node-exporter|node-exporter-nodes\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table",
   "description": "All nodes' perfomance at a glance.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"} \n* on (cluster,job,instance)\ngroup_left(pretty_name)\nnode_os_info{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}\n"
    },
    {
     "expr": "time() - node_boot_time_seconds{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_load1{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    },
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"})\n* 100\n)\n"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}"
    },
    {
     "expr": "100 - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=~\"node-exporter|node-exporter-nodes\",instance=~\"$instance\"}*100"
    }
   ]
  },
  { "title": "Fleet & Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remnawave_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_users_status{status=\"ACTIVE\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(remnawave_node_online_users)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Прирост пользователей",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(marzban_panel_users_active[30d])",
     "legendFormat": "Users"
    },
    {
     "expr": "delta(remnawave_users_total[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "count(count_over_time(marzban_user_online[30d:1d]) > 0)",
     "legendFormat": "Users"
    },
    {
     "expr": "count(count_over_time(remnawave_users_status{status=\"ACTIVE\"}[30d:1d]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_node_status",
     "legendFormat": "{{node_country_emoji}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_node_online_users",
     "legendFormat": "{{node_country_emoji}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(marzban_user_online==1)", "legendFormat": "Users" },
    {
     "expr": "sum(remnawave_node_online_users)",
     "legendFormat": "Users"
    }
   ]
  }
 ]
}